name: Build, Test & Publish

on:
  push:
    paths:
    - 'src/**'
    - '.github/workflows/**'
    branches: [ main ]
  pull_request:
    paths:
    - 'src/**'
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    permissions:
      id-token: write

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
    - name: Build
      working-directory: ./src
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./src
      run: |
        dotnet test --configuration Release --no-restore --no-build --verbosity normal --logger trx || true
    - name: Test Report
      uses: dorny/test-reporter@v3
      if: always()
      with:
        name: 'DotNET Tests ${{ matrix.os }}'
        path: "**/*.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
    - name: Build project and generate NuGet package
      if: matrix.os == 'ubuntu-latest'
      run: |
        dotnet pack --configuration Release --output $GITHUB_WORKSPACE/out src/Nager.TcpClient/Nager.TcpClient.csproj
    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{secrets.NUGET_USER}}
    - name: Push NuGet package
      if: github.event_name != 'pull_request' && matrix.os == 'ubuntu-latest'
      run: |
        cd $GITHUB_WORKSPACE/out
        dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{steps.login.outputs.NUGET_API_KEY}} --skip-duplicate --no-symbols
